trigger:
  branches:
    include:
    - main

stages:
 - stage: Dev
   jobs:
   - job: TerraformPlan
     steps:

     - script: 'terraform -chdir=main/ init -input=false'
       displayName: 'Init'
       env:
         ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
         ARM_TENANT_ID: $(ARM_TENANT_ID)
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
